export const equipment = [
  {
    name: "GRIGRI® +",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/GRIGRI-PLUS",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "GRIGRI®",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/GRIGRI",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "REVERSO®",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/REVERSO",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "VERSO",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/VERSO",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "HUIT",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/HUIT",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "HUIT ANTIBRULURE",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/HUIT-ANTIBRULURE",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "STOP",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/STOP",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "SIMPLE",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/SIMPLE",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "RACK",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/RACK",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "FREINO Z",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/FREINO-Z",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "Pulley for SIMPLE",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/Pulley-for-SIMPLE",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "Swinging brake bar with hook for RACK",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/Swinging-brake-bar-with-hook-for-RACK",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "Brake bar w/o hook for RACK",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/Brake-bar-w-o-hook-for-RACK",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "Anodized, fixed brake bar for RACK",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/Anodized--fixed-brake-bar-for-RACK",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "PIRANA CLUB",
    link: "https://www.Petzl.com/GB/en/Sport/Belay-Devices-And-Descenders/PIRANA-CLUB",
    brand: "Petzl",
    type: "belay",
  },
  {
    name: "ATC-Guide Belay/Rappel Device",
    link: "https://www.blackdiamondequipment.com//en_GB/product/atc-guide-belay-rappel-device/?colorid=3104",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "ATC-Alpine Guide",
    link: "https://www.blackdiamondequipment.com//en_GB/product/atc-alpine-guide/",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "Big Air Pilot Package",
    link: "https://www.blackdiamondequipment.com//en_GB/product/big-air-pilot-package-1/",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "Big Air XP Package",
    link: "https://www.blackdiamondequipment.com//en_GB/product/big-air-xp-package/",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "ATC-XP Belay/Rappel Device",
    link: "https://www.blackdiamondequipment.com//en_GB/product/atc-xp-belay-rappel-device/?colorid=3111",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "ATC Belay/Rappel Device",
    link: "https://www.blackdiamondequipment.com//en_GB/product/atc-belay-rappel-device/?colorid=3109",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "Super 8 Belay/Rappel Device",
    link: "https://www.blackdiamondequipment.com//en_GB/product/super-8-belay-rappel-device/?colorid=3107",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "PearLock Screwgate Carabiner",
    link: "https://www.blackdiamondequipment.com//en_GB/product/pearlock-screwgate-carabiner/?colorid=5480",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "GridLock Screwgate Carabiner",
    link: "https://www.blackdiamondequipment.com//en_GB/product/gridlock-screwgate-carabiner/?colorid=2542",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "VaporLock Screwgate Carabiner",
    link: "https://www.blackdiamondequipment.com//en_GB/product/vaporlock-screwgate-carabiner/",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "RockLock Screwgate Carabiner",
    link: "https://www.blackdiamondequipment.com//en_GB/product/rocklock-screwgate-carabiner/?colorid=2541",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "ATC Pilot",
    link: "https://www.blackdiamondequipment.com//en_GB/product/atc-pilot/",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "RockLock Twistlock Carabiner",
    link: "https://www.blackdiamondequipment.com//en_GB/product/rocklock-twistlock-carabiner/",
    brand: "Black-Diamond",
    type: "belay",
  },
  {
    name: "Momentum Harness - Men's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-harness-mens/?colorid=3359",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum Harness - Women's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-harness-womens/?colorid=3365",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Solution Harness - Men's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/solution-mens/?colorid=5450",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Solution Harness - Women's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/solution-womens/?colorid=5452",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Long Haul Harness",
    link: "https://www.blackdiamondequipment.com//en_GB/product/long-haul-harness/?colorid=9800",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Zone Harness - Women's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/zone-harness-womens-1/?colorid=5463",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Zone Harness - Men's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/zone-harness-mens/?colorid=5458",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Solution Harness - Women's - Babsi Edition",
    link: "https://www.blackdiamondequipment.com//en_GB/product/solution-harness-womens-babsi-edition/?colorid=5453",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Couloir UL",
    link: "https://www.blackdiamondequipment.com//en_GB/product/couloir-ul/?colorid=6066",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Couloir 3S",
    link: "https://www.blackdiamondequipment.com//en_GB/product/couloir-3s/?colorid=6380",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Couloir",
    link: "https://www.blackdiamondequipment.com//en_GB/product/couloir/?colorid=6374",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum 4s Harness Package",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-4s-harness-package/?colorid=3400",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum Harness - Women's Package",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-harness-ws-package/?colorid=3395",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum Harness - Men's Package",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-harness-ms-package/?colorid=3389",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Technician RECCO",
    link: "https://www.blackdiamondequipment.com//en_GB/product/technician-recco/?colorid=6060",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Couloir LT",
    link: "https://www.blackdiamondequipment.com//en_GB/product/couloir-lt/?colorid=6369",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Airnet Harness - Women's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/airnet-harness-womens/?colorid=4432",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Airnet Harness - Men's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/airnet-harness-mens/?colorid=3380",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum 4s Harness",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-4s-harness/?colorid=3379",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum 3s Harness - Women's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-3s-harness-womens/?colorid=3374",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum 3s Harness - Men's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-3s-harness-mens/?colorid=3368",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Momentum Harness - Kid's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/momentum-harness-kids/?colorid=3367",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Vision Harness",
    link: "https://www.blackdiamondequipment.com//en_GB/product/vision-harness/?colorid=3348",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "Solution Guide Harness - Men's",
    link: "https://www.blackdiamondequipment.com//en_GB/product/solution-guide-harness-mens/?colorid=3337",
    brand: "Black-Diamond",
    type: "harness",
  },
  {
    name: "SITTA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/SITTA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "AQUILA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/AQUILA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "HIRUNDOS",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/HIRUNDOS",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "FLY",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/FLY",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "ADJAMA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/ADJAMA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "LUNA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/LUNA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "SAMA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/SAMA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "SELENA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/SELENA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "ALTITUDE®",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/ALTITUDE",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "CORAX",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CORAX",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "TOUR",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/TOUR",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "8003",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/8003",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "VOLTIGE",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/VOLTIGE",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "MACCHU®",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/MACCHU",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "BODY",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/OUISTITI",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "OUISTITI",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/SIMBA",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "SIMBA",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/AVEN",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "AVEN",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/SUPERAVANTI",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "SUPERAVANTI",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/EXPLO",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "EXPLO",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/TORSE",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "TORSE",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CANYON-CLUB",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "CANYON CLUB",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CANYON-GUIDE",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "CANYON GUIDE",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/Protective-seat-for-CANYON-harnesses",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "Protective seat for CANYON harnesses",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/Equipment-holder-for-CANYON-CLUB-harness",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "Comfort foam for CANYON CLUB harness",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/Cutaway-sling-for-CANYON-CLUB-harness",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "Equipment holder for CANYON CLUB harness",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/Cutaway-sling-for-CANYON-GUIDE-harness",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "Cutaway sling for CANYON CLUB harness",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CARITOOL",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "Cutaway sling for CANYON GUIDE harness",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CARITOOL-EVO",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "CARITOOL",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CARITOOL-EVO",
    brand: "Petzl",
    type: "harness",
  },
  {
    name: "CARITOOL EVO",
    link: "https://www.Petzl.com/GB/en/Sport/Harnesses/CARITOOL-EVO",
    brand: "Petzl",
    type: "harness",
  },
];

export function getEquipment() {
  return equipment.map((e) => e);
}
